version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - observability

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    volumes:
      - ./configs/loki-config.yaml:/etc/loki/local-config.yaml:ro
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    ports:
      - '3100:3100'
    networks:
      - observability

  tempo:
    image: grafana/tempo:1.6.0
    container_name: tempo
    volumes:
      - ./configs/tempo-config.yaml:/etc/tempo/local-config.yaml:ro
    command:
      - '-config.file=/etc/tempo/local-config.yaml'
    ports:
      - '3200:3200'
    networks:
      - observability

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./configs/otel-config.yaml:/etc/otel-collector-config.yaml:ro
    command:
      - '--config=/etc/otel-collector-config.yaml'
    ports:
      - '4317:4317'   # OTLP gRPC receiver
      - '55680:55680' # OTLP HTTP receiver
      - '8888:8888'   # health & metrics
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - prometheus
      - loki
      - tempo
    ports:
      - '3000:3000'
    networks:
      - observability

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - observability


networks:
  observability:
    driver: bridge
