# configs/tempo-config.yaml

server:
  http_listen_port: 3200
  grpc_listen_port: 9095
  register_instrumentation: true

distributor:
  receivers:
    otlp:
      protocols:
        grpc:    # OTLP/gRPC
          endpoint: 0.0.0.0:4317
        http:    # OTLP/HTTP
          endpoint: 0.0.0.0:4318

ingester:
  trace_idle_period: 10s

compactor:
  compaction:
    compaction_window: 1h

storage:
  trace:
    backend: local
    local:
      path: /tempo-data

memberlist:
  join_members: []
